version: '3.8'

services:
  run-model-locally:
    container_name: association-model-local-starter
    restart: "no"
    image: tianon/true
    depends_on:
      - association-model

  association-model:
    container_name: association-model
    build:
      context: .
    restart: unless-stopped
    volumes:
      - .:/app-workspace
    env_file:
      - .env
    networks:
      - tourmanique-api-private_tourmanique-net

networks:
  tourmanique-api-private_tourmanique-net:
    external: true